# Generated by Django 5.0.6 on 2024-06-20 17:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("administracao", "0002_alter_servico_procentagem_comissao_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="servico",
            old_name="procentagem_comissao",
            new_name="porcentagem_comissao",
        ),
    ]
